import { Project, ProjectCategory, ProjectStatus, User, ActivityType, Proposal, ProposalStatus } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'DeFi Yield Aggregator',
    slug: 'defi-yield-aggregator',
    short_description: 'A smart contract-based platform to optimize yield farming across multiple DeFi protocols.',
    description: 'Our project aims to build a state-of-the-art DeFi yield aggregator. By automatically shifting funds between protocols like Aave, Compound, and Yearn, we provide users with the best possible returns on their crypto assets. The platform will feature a simple UI, low gas fees, and robust security audits.',
    thumbnail: 'https://picsum.photos/seed/defi1/400/400',
    banner: 'https://picsum.photos/seed/defi-banner1/1200/600',
    category: ProjectCategory.DeFi,
    goal_amount_xrp: 50000,
    raised_amount_xrp: 37500,
    xrpl_wallet: 'r...',
    status: ProjectStatus.Active,
    donors: 152,
    socials: { twitter: '#', website: '#', linkedin: '#' },
    team: [
        { name: 'Alice Johnson', role: 'Lead Developer', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Alice' },
        { name: 'Bob Williams', role: 'Smart Contract Engineer', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Bob' },
        { name: 'Charlie Brown', role: 'UI/UX Designer', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Charlie' },
    ]
  },
  {
    id: '2',
    title: 'PixelVerse Adventures',
    slug: 'pixelverse-adventures',
    short_description: 'A retro-style 2D MMORPG with blockchain-integrated items and economy.',
    description: 'PixelVerse Adventures is a nostalgic journey back to the golden age of 2D gaming, enhanced with modern blockchain technology. Players can own land, craft unique items as NFTs, and participate in a player-driven economy. All in-game assets are tradable on the XRPL DEX.',
    thumbnail: 'https://picsum.photos/seed/gamefi1/400/400',
    banner: 'https://picsum.photos/seed/gamefi-banner1/1200/600',
    category: ProjectCategory.GameFi,
    goal_amount_xrp: 75000,
    raised_amount_xrp: 75000,
    xrpl_wallet: 'r...',
    status: ProjectStatus.Completed,
    donors: 843,
    socials: { twitter: '#', website: '#' },
    team: [
        { name: 'Diana Miller', role: 'Game Director', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Diana' },
        { name: 'Ethan Davis', role: 'Lead Game Developer', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Ethan' },
        { name: 'Fiona Garcia', role: 'Pixel Artist', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Fiona' },
        { name: 'George Rodriguez', role: 'Community Manager', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=George' },
    ]
  },
  {
    id: '3',
    title: 'CryptoKids Education',
    slug: 'cryptokids-education',
    short_description: 'An interactive platform to teach children about blockchain and cryptocurrency safely.',
    description: 'We believe financial literacy in the digital age starts with understanding blockchain. CryptoKids provides fun, gamified lessons on topics like decentralization, wallets, and smart contracts. Our platform is a safe, simulated environment where kids can learn without risking real assets.',
    thumbnail: 'https://picsum.photos/seed/edu1/400/400',
    banner: 'https://picsum.photos/seed/edu-banner1/1200/600',
    category: ProjectCategory.Education,
    goal_amount_xrp: 20000,
    raised_amount_xrp: 12000,
    xrpl_wallet: 'r...',
    status: ProjectStatus.Active,
    donors: 210,
    socials: { website: '#' },
    team: [
        { name: 'Hannah Wilson', role: 'Founder & Educator', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Hannah' },
        { name: 'Ian Martinez', role: 'Lead Developer', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Ian' },
    ]
  },
  {
    id: '4',
    title: 'Generative Art NFT Collection',
    slug: 'generative-art-nft',
    short_description: 'A unique collection of 10,000 NFTs generated by a novel AI algorithm on the XRPL.',
    description: 'This project fuses art and technology to create a one-of-a-kind NFT collection. Each piece is generated based on a unique hash, ensuring no two are alike. Holders will gain access to an exclusive community and future airdrops. Funds will be used to further develop the AI art generator.',
    thumbnail: 'https://picsum.photos/seed/nft1/400/400',
    banner: 'https://picsum.photos/seed/nft-banner1/1200/600',
    category: ProjectCategory.NFT,
    goal_amount_xrp: 30000,
    raised_amount_xrp: 29500,
    xrpl_wallet: 'r...',
    status: ProjectStatus.Active,
    donors: 567,
    socials: { twitter: '#', website: '#' },
    team: [
        { name: 'Jack Anderson', role: 'Generative Artist', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Jack' },
        { name: 'Karen Taylor', role: 'Project Manager', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Karen' },
    ]
  },
  {
    id: '5',
    title: 'Clean Water Initiative',
    slug: 'clean-water-initiative',
    short_description: 'Transparently funding and tracking clean water projects in developing nations via blockchain.',
    description: 'Leveraging the XRPL for its low fees and transparency, this project ensures that 100% of donations go directly to funding wells and water purification systems. Every donation is tracked on-chain, and donors can see the real-world impact of their contribution through verified project updates.',
    thumbnail: 'https://picsum.photos/seed/charity1/400/400',
    banner: 'https://picsum.photos/seed/charity-banner1/1200/600',
    category: ProjectCategory.Charity,
    goal_amount_xrp: 100000,
    raised_amount_xrp: 45000,
    xrpl_wallet: 'r...',
    status: ProjectStatus.Active,
    donors: 432,
    socials: { twitter: '#', website: '#', linkedin: '#' },
    team: [
        { name: 'Liam Thomas', role: 'Project Coordinator', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Liam' },
        { name: 'Mia Hernandez', role: 'Operations Lead', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Mia' },
        { name: 'Noah Moore', role: 'On-ground Partner', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Noah' },
    ]
  },
  {
    id: '6',
    title: 'XRPL DEX Aggregator',
    slug: 'xrpl-dex-aggregator',
    short_description: 'Find the best swap rates across all decentralized exchanges on the XRP Ledger.',
    description: 'As the XRPL ecosystem grows, finding the best trading rates becomes complex. Our DEX aggregator will scan all available liquidity pools to provide users with the most efficient trading path, minimizing slippage and maximizing returns. It\'s a crucial tool for any serious XRPL trader.',
    thumbnail: 'https://picsum.photos/seed/defi2/400/400',
    banner: 'https://picsum.photos/seed/defi-banner2/1200/600',
    category: ProjectCategory.DeFi,
    goal_amount_xrp: 60000,
    raised_amount_xrp: 15000,
    xrpl_wallet: 'r...',
    status: ProjectStatus.Active,
    donors: 88,
    socials: { twitter: '#', github: '#' },
    team: [
        { name: 'Olivia Martin', role: 'Lead Quant Developer', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Olivia' },
        { name: 'Peter Jackson', role: 'Backend Engineer', avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Peter' },
    ]
  }
];

export const MOCK_USER_DATA: User = {
  address: 'rPsmM2HL2cAkFfcsM62aV8a25d2oT61gA4',
  xrpBalance: 1234.56,
  fortBalance: 5678,
  avatarUrl: `https://api.dicebear.com/8.x/bottts/svg?seed=rPsmM2HL2cAkFfcsM62aV8a25d2oT61gA4`,
  donations: [
    { projectId: '1', amountXRP: 500, date: '2024-07-15T10:30:00Z' },
    { projectId: '4', amountXRP: 1000, date: '2024-07-10T14:00:00Z' },
    { projectId: '5', amountXRP: 250, date: '2024-06-28T09:15:00Z' },
  ],
  activityLog: [
      { id: 'act1', type: ActivityType.Donation, description: 'Donated to DeFi Yield Aggregator', date: '2024-07-15T10:30:00Z', amountXRP: 500 },
      { id: 'act2', type: ActivityType.Vote, description: 'Voted on Proposal #102: New Funding Round', date: '2024-07-12T18:00:00Z' },
      { id: 'act3', type: ActivityType.Donation, description: 'Donated to Generative Art NFT Collection', date: '2024-07-10T14:00:00Z', amountXRP: 1000 },
      { id: 'act4', type: ActivityType.Donation, description: 'Donated to Clean Water Initiative', date: '2024-06-28T09:15:00Z', amountXRP: 250 },
      { id: 'act5', type: ActivityType.Vote, description: 'Voted on Proposal #98: Community Guidelines Update', date: '2024-06-20T11:45:00Z' },
  ]
};

const threeDaysFromNow = new Date();
threeDaysFromNow.setDate(threeDaysFromNow.getDate() + 3);

const tenDaysFromNow = new Date();
tenDaysFromNow.setDate(tenDaysFromNow.getDate() + 10);

const fiveDaysAgo = new Date();
fiveDaysAgo.setDate(fiveDaysAgo.getDate() - 5);

const tenDaysAgo = new Date();
tenDaysAgo.setDate(tenDaysAgo.getDate() - 10);

export const MOCK_PROPOSALS: Proposal[] = [
    {
        id: 'prop-101',
        title: 'Increase Project Submission Fee to 50 FORT',
        proposer: 'rPsmM2HL2cAkFfcsM62aV8a25d2oT61gA4',
        description: 'To reduce spam and ensure higher quality project submissions, this proposal suggests increasing the fee to create a new project from 10 FORT to 50 FORT. This will help curate more serious projects for the community to consider.',
        status: ProposalStatus.Active,
        votesFor: 125000,
        votesAgainst: 30000,
        endDate: threeDaysFromNow.toISOString(),
    },
    {
        id: 'prop-102',
        title: 'Allocate 200,000 XRP from Treasury for GameFi Development Grants',
        proposer: 'rH_some_other_address_placeholder',
        description: 'The GameFi sector is rapidly growing. This proposal seeks to allocate 200,000 XRP from the DAO treasury to a dedicated grant program for promising GameFi projects building on the XRPL. A committee will be formed to oversee the grant distribution.',
        status: ProposalStatus.Active,
        votesFor: 88000,
        votesAgainst: 65000,
        endDate: tenDaysFromNow.toISOString(),
    },
    {
        id: 'prop-100',
        title: 'Partnership with "XRPL Nexus" for Marketing',
        proposer: 'rAnotherAddressHereForProposals',
        description: 'This proposal outlines a strategic marketing partnership with XRPL Nexus, a leading XRPL community hub. The goal is to increase Fortuna DAO\'s visibility and attract more high-quality projects and donors.',
        status: ProposalStatus.Passed,
        votesFor: 350000,
        votesAgainst: 25000,
        endDate: fiveDaysAgo.toISOString(),
    },
    {
        id: 'prop-99',
        title: 'Update Community Moderation Guidelines',
        proposer: 'rYetAnotherOneForGoodMeasure',
        description: 'A proposal to revise and update the community guidelines for Discord and other social channels to ensure a safe and productive environment for all members.',
        status: ProposalStatus.Executed,
        votesFor: 210000,
        votesAgainst: 5000,
        endDate: tenDaysAgo.toISOString(),
    },
    {
        id: 'prop-98',
        title: 'Reduce Quorum Threshold to 5% for Minor Proposals',
        proposer: 'rFinalAddressForMockDataList',
        description: 'To speed up decision-making on non-critical issues, this proposal suggests lowering the required quorum from 10% to 5% of total FORT supply for proposals tagged as "minor".',
        status: ProposalStatus.Failed,
        votesFor: 40000,
        votesAgainst: 180000,
        endDate: tenDaysAgo.toISOString(),
    }
];